<?php

namespace Database\Seeders\Heirloom;

use App\Models\Heirloom\HeirloomEffectSummary;
use Illuminate\Database\Seeder;

class HeirloomEffectSummarySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $heirloomEffectSummaries = [
            [
                'heirloom_id' => 1,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 2,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 2,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 9,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 3,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 3,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 10,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 4,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 4,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 11,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 5,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 5,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 12,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 6,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 6,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 13,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 7,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 7,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 14,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 8,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 8,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 15,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 9,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 9,
                'heirloom_effect_description_id' => 2,
                'heirloom_effect_category_id' => 10,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 10,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 10,
                'heirloom_effect_description_id' => 3,
                'heirloom_effect_category_id' => 11,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 11,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 11,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 12,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 12,
                'heirloom_effect_description_id' => 5,
                'heirloom_effect_category_id' => 2,
                'activation_condition_id' => 8,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 13,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 13,
                'heirloom_effect_description_id' => 6,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 17,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 14,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 14,
                'heirloom_effect_description_id' => 7,
                'heirloom_effect_category_id' => 12,
                'activation_condition_id' => 16,
                'effect_target_id' => 5,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 15,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 15,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 19,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 16,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 16,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 23,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 17,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 18,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 18,
                'heirloom_effect_description_id' => 9,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 17,
                'effect_target_id' => 6,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 19,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 19,
                'heirloom_effect_description_id' => 10,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 18,
                'effect_target_id' => 7,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 20,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 20,
                'heirloom_effect_description_id' => 2,
                'heirloom_effect_category_id' => 10,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 21,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 21,
                'heirloom_effect_description_id' => 11,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 1,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 22,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 22,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 2,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 23,
                'heirloom_effect_description_id' => 13,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 23,
                'heirloom_effect_description_id' => 13,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 3,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 24,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 24,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 4,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 25,
                'heirloom_effect_description_id' => 13,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 25,
                'heirloom_effect_description_id' => 14,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 5,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 26,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 26,
                'heirloom_effect_description_id' => 16,
                'heirloom_effect_category_id' => 13,
                'activation_condition_id' => 6,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 27,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 27,
                'heirloom_effect_description_id' => 17,
                'heirloom_effect_category_id' => 14,
                'activation_condition_id' => 8,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 28,
                'heirloom_effect_description_id' => 18,
                'heirloom_effect_category_id' => 22,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 28,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 8,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 29,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 29,
                'heirloom_effect_description_id' => 19,
                'heirloom_effect_category_id' => 15,
                'activation_condition_id' => 22,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 30,
                'heirloom_effect_description_id' => 18,
                'heirloom_effect_category_id' => 22,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 30,
                'heirloom_effect_description_id' => 20,
                'heirloom_effect_category_id' => 16,
                'activation_condition_id' => 23,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 31,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 32,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 32,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 1,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 33,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 33,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 2,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 34,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 34,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 3,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 35,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 35,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 4,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 36,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 36,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 5,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 37,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 37,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 6,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 38,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 38,
                'heirloom_effect_description_id' => 2,
                'heirloom_effect_category_id' => 10,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 39,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 39,
                'heirloom_effect_description_id' => 11,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 40,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 40,
                'heirloom_effect_description_id' => 23,
                'heirloom_effect_category_id' => 17,
                'activation_condition_id' => 7,
                'effect_target_id' => 8,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 41,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 41,
                'heirloom_effect_description_id' => 24,
                'heirloom_effect_category_id' => 18,
                'activation_condition_id' => 7,
                'effect_target_id' => 9,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 42,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 42,
                'heirloom_effect_description_id' => 25,
                'heirloom_effect_category_id' => 19,
                'activation_condition_id' => 7,
                'effect_target_id' => 10,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 43,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 43,
                'heirloom_effect_description_id' => 26,
                'heirloom_effect_category_id' => 20,
                'activation_condition_id' => 7,
                'effect_target_id' => 11,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 44,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 44,
                'heirloom_effect_description_id' => 18,
                'heirloom_effect_category_id' => 22,
                'activation_condition_id' => 1,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 45,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 45,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 2,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 46,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 46,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 3,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 47,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 47,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 4,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 48,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 48,
                'heirloom_effect_description_id' => 19,
                'heirloom_effect_category_id' => 15,
                'activation_condition_id' => 5,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 49,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 49,
                'heirloom_effect_description_id' => 27,
                'heirloom_effect_category_id' => 21,
                'activation_condition_id' => 6,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 50,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 50,
                'heirloom_effect_description_id' => 28,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 8,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 51,
                'heirloom_effect_description_id' => 29,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 52,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 53,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 53,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 9,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 54,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 54,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 10,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 55,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 55,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 11,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 56,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 56,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 12,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 57,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 57,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 13,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 58,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 58,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 14,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 59,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 59,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 15,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 60,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 60,
                'heirloom_effect_description_id' => 2,
                'heirloom_effect_category_id' => 10,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 61,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 61,
                'heirloom_effect_description_id' => 15,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 62,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 62,
                'heirloom_effect_description_id' => 3,
                'heirloom_effect_category_id' => 11,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 63,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 63,
                'heirloom_effect_description_id' => 21,
                'heirloom_effect_category_id' => 3,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 64,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 64,
                'heirloom_effect_description_id' => 18,
                'heirloom_effect_category_id' => 22,
                'activation_condition_id' => 24,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 65,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 65,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 25,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 66,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 67,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 67,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 9,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 68,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 68,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 10,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 69,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 69,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 11,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 70,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 70,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 12,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 71,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 71,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 13,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 72,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 72,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 14,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 73,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 73,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 15,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 74,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 74,
                'heirloom_effect_description_id' => 2,
                'heirloom_effect_category_id' => 10,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 75,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 75,
                'heirloom_effect_description_id' => 30,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 76,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 76,
                'heirloom_effect_description_id' => 3,
                'heirloom_effect_category_id' => 11,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 77,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 77,
                'heirloom_effect_description_id' => 31,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 12,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 78,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 78,
                'heirloom_effect_description_id' => 11,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 8,
                'effect_target_id' => 4,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 79,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 79,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 23,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 80,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 81,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 81,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 9,
                'effect_target_id' => 2,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 82,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 82,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 10,
                'effect_target_id' => 2,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 83,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 83,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 11,
                'effect_target_id' => 2,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 84,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 84,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 12,
                'effect_target_id' => 2,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 85,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 85,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 13,
                'effect_target_id' => 2,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 86,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 86,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 14,
                'effect_target_id' => 2,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 87,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 87,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 15,
                'effect_target_id' => 2,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 88,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 88,
                'heirloom_effect_description_id' => 2,
                'heirloom_effect_category_id' => 10,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 89,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 89,
                'heirloom_effect_description_id' => 3,
                'heirloom_effect_category_id' => 11,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 90,
                'heirloom_effect_description_id' => 33,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 90,
                'heirloom_effect_description_id' => 2,
                'heirloom_effect_category_id' => 10,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 91,
                'heirloom_effect_description_id' => 34,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 91,
                'heirloom_effect_description_id' => 2,
                'heirloom_effect_category_id' => 10,
                'activation_condition_id' => 7,
                'effect_target_id' => 3,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 92,
                'heirloom_effect_description_id' => 33,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 92,
                'heirloom_effect_description_id' => 35,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 8,
                'effect_target_id' => 13,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 93,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 93,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 22,
                'effect_target_id' => 1,
                'effect_classification' => 1,
            ],
            [
                'heirloom_id' => 94,
                'heirloom_effect_description_id' => 1,
                'heirloom_effect_category_id' => 1,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 95,
                'heirloom_effect_description_id' => 4,
                'heirloom_effect_category_id' => 4,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 96,
                'heirloom_effect_description_id' => 12,
                'heirloom_effect_category_id' => 5,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 97,
                'heirloom_effect_description_id' => 22,
                'heirloom_effect_category_id' => 6,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 98,
                'heirloom_effect_description_id' => 8,
                'heirloom_effect_category_id' => 7,
                'activation_condition_id' => 7,
                'effect_target_id' => 1,
                'effect_classification' => 0,
            ],
            [
                'heirloom_id' => 99,
                'heirloom_effect_description_id' => 32,
                'heirloom_effect_category_id' => 9,
                'activation_condition_id' => 7,
                'effect_target_id' => 2,
                'effect_classification' => 0,
            ],
        ];
        HeirloomEffectSummary::upsert(
            $heirloomEffectSummaries,
            ['heirloom_id', 'heirloom_effect_category_id', 'activation_condition_id', 'effect_target_id', 'effect_classification'],
            []
        );
    }
}
